# Generated by Django 5.1 on 2024-12-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productmodel_deal_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
