# Generated by Django 5.1 on 2024-12-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
