# Generated by Django 5.1 on 2024-12-12 11:23

import store.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cartmodel_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='is ordered'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='deal_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='deal end date'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='deal_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='deal start date'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='discount price'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is featured'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='is new'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='is on sale'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='month_of_deal',
            field=models.BooleanField(default=False, verbose_name='month of deal'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='real_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='real price'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sale_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='sale end date'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sale_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='sale start date'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sold',
            field=models.PositiveIntegerField(default=0, verbose_name='sold'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='available', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='productresultmodel',
            name='overall_rating',
            field=models.FloatField(default=0.0, verbose_name='overall rating'),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='rating',
            field=models.FloatField(validators=[store.utils.validate_score], verbose_name='rating'),
        ),
    ]
