# Generated by Django 5.1 on 2024-12-12 11:23

import contact.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='location',
            field=models.CharField(max_length=150, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[contact.utils.phone_number_validation], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='is_solved',
            field=models.BooleanField(default=False, verbose_name='is solved'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[contact.utils.phone_number_validation], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sent_to_check'), (2, 'In_progress'), (3, 'Checked')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
