# Generated by Django 5.1 on 2024-12-09 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for the coupon.', max_length=50, unique=True)),
                ('discount', models.FloatField(help_text='Discount percentage (e.g., 20 for 20%).', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('valid_from', models.DateTimeField(help_text='Start date and time for coupon validity.')),
                ('valid_to', models.DateTimeField(help_text='End date and time for coupon validity.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the coupon is currently active.')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Customer's first name.", max_length=50)),
                ('last_name', models.CharField(help_text="Customer's last name.", max_length=50)),
                ('email', models.EmailField(help_text="Customer's email address.", max_length=254)),
                ('phone', models.CharField(help_text="Customer's phone number.", max_length=20)),
                ('address1', models.TextField(help_text='Primary address line.')),
                ('address2', models.TextField(blank=True, help_text='Secondary address line (optional).', null=True)),
                ('city', models.CharField(help_text="City of the customer's address.", max_length=50)),
                ('country', models.CharField(help_text="Country of the customer's address.", max_length=50)),
                ('zip_code', models.CharField(help_text="Postal/ZIP code of the customer's address.", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the order was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the order was last updated.')),
                ('coupon', models.ForeignKey(blank=True, help_text='Coupon applied to the order, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='checkout.couponmodel')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product.', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the product.', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.FloatField(help_text='Price per unit of the product.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('order', models.ForeignKey(help_text='The order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.ordermodel')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
                'db_table': 'orderitem',
            },
        ),
    ]
