# Generated by Django 5.1 on 2024-12-10 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('store', '0005_wishlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='price',
            field=models.FloatField(default=0, help_text='Price per unit of the product.', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product_name',
            field=models.ManyToManyField(to='store.productmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of the product.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='OrderItemModel',
        ),
    ]
