# Generated by Django 5.1 on 2024-12-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_ordermodel_price_ordermodel_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='valid_to',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.couponmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
