# Generated by Django 5.1 on 2024-12-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_ordermodel_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='address1',
            new_name='address',
        ),
    ]
