# Generated by Django 5.1 on 2024-12-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_couponmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
