# Generated by Django 5.1 on 2024-12-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_couponmodel_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
