# Generated by Django 5.1 on 2024-12-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_picture',
            field=models.ImageField(default='img/default_user_image.png', upload_to='profile_pictures'),
        ),
    ]
