# Generated by Django 5.1 on 2024-12-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profilemodel_first_name_profilemodel_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='age',
        ),
    ]
