# Generated by Django 5.1 on 2024-12-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_profilemodel_address_alter_profilemodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='age'),
        ),
    ]
